name: "Compliance"

on:
  pull_request_target:
    types:
      - opened
      - edited
      - synchronize

permissions:
  pull-requests: write

jobs:
  compliance:
    uses: open-sauced/hot/.github/workflows/compliance.yml@main
name: reviewdog
on: [pull_request]
  
  vale:
    name: runner / vale
    runs-on: ubuntu-latest
    steps:
    - name: linting 
      - uses: actions/checkout@v3
      - uses: errata-ai/vale-action@reviewdog
         files: "* .md"