name: Compliance

on:
  pull_request_target:
    types: [opened, edited]

permissions:
  pull-requests: write

jobs:
  compliance:
    uses: open-sauced/hot/.github/workflows/compliance.yml@main
    name: reviewdog

  vale:
    name: runner / vale
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: linting
        uses: errata-ai/vale-action@reviewdog
        with:
          files: "*.md"
