name: "Compliance"

on:
  pull_request_target:
    types:
      - opened
      - edited
      - synchronize

permissions:
  pull-requests: write

jobs:
  compliance:
    uses: open-sauced/hot/.github/workflows/compliance.yml@main
    name: reviewdog
    on: [pull_request]

  vale:
    name: runner / vale
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: linting 
        uses: errata-ai/vale-action@reviewdog
        files: "* .md"